# Non-Graded Challenge 4 Matrix
Wirawan Setio Aji <br>
Batch014

## Soal
1. Membuat tensor seperti : [[[23 ,50],[7 ,12]],[[57 ,67],[99,43]],[[75, 21],[57,12]],[[87,26],[18,84]]]
2. ProblemsHacktiv8 DS Curriculum Team2. Lakukan perkalian terhadap matrix berikut: 
    - A [[23,50,19],[7,12,109],[57,67,98]]
    - B [[17],[22],[19]] 
3. Diketahui A =[[23,50,19],[7,12,109],[59,67,98]]
    - Transpose
    - Determinant
    - Inverse

## import library 
kali ini menggunakan Numpy

In [1]:
import numpy as np

## Jawaban

**jawab Nomor 1**

In [3]:
# arrays [[[23 ,50],[7 ,12]],[[57 ,67],[99,43]],[[75, 21],[57,12]],[[87,26],[18,84]]]
M1 = np.array([[23 ,50],[7 ,12]])
M2 = np.array([[57 ,67],[99,43]])
M3 = np.array([[75, 21],[57,12]])
M4 = np.array([[87,26],[18,84]])

# membuat Tensor
tensor3d = np.array([M1,M2,M3,M4])
tensor3d

array([[[23, 50],
        [ 7, 12]],

       [[57, 67],
        [99, 43]],

       [[75, 21],
        [57, 12]],

       [[87, 26],
        [18, 84]]])

**Jawaban No.2**

In [11]:
A = np.array([[23,50,19],[7,12,109],[57,67,98]])
B = np.array([[17],[22],[19]])
print(B)
A@B

[[17]
 [22]
 [19]]


array([[1852],
       [2454],
       [4305]])

**Soal No.3**

In [14]:
A = np.array([[23,50,19],[7,12,109],[59,67,98]])
A

array([[ 23,  50,  19],
       [  7,  12, 109],
       [ 59,  67,  98]])

- Transpose

In [13]:
A.T

array([[ 23,   7,  59],
       [ 50,  12,  67],
       [ 19, 109,  98]])

- Determinant

In [23]:
np.linalg.det(A)

141787.99999999994

- Inverse

In [24]:
A_i = np.linalg.inv(A)
A_i

array([[-0.0432124 , -0.02558044,  0.03682963],
       [ 0.04051824,  0.0079908 , -0.01674331],
       [-0.00168562,  0.00993737, -0.00052191]])

In [21]:
A @ A_i

array([[1.00000000e+00, 0.00000000e+00, 4.85722573e-17],
       [8.32667268e-17, 1.00000000e+00, 3.46944695e-17],
       [2.77555756e-17, 0.00000000e+00, 1.00000000e+00]])